# Use public Python 3.10 image
FROM python:3.10-slim

# Set a non-interactive frontend for apt
ARG DEBIAN_FRONTEND=noninteractive

# Install required dependencies for system and Poetry
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg \
        libimage-exiftool-perl \
        libsm6 \
        libxext6 \
        curl \
        git \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

# Set up the working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml poetry.lock /app/
COPY reflectdetect /app/reflectdetect

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Set the entry point to your CLI tool
ENTRYPOINT ["reflectdetect-converter"]

# Default command processes a folder
CMD ["/data"]
