PANEL_PROPERTIES_FILENAME = "panel_properties.json"
PANEL_LOCATIONS_FILENAME = "panel_locations.gpkg"
IMAGES_FOLDER = "images"
ORTHOPHOTO_FOLDER = "orthophotos"
COMPRESSION_FACTOR = (
    10000  # convert from 0.1234 to 1234 TODO: Document compression factor
)
DEFAULT_TAG_DIRECTION = "up"
DEFAULT_TAG_FAMILY = "tag25h9"
DEFAULT_SHRINK_FACTOR = 0.8
DEFAULT_PANEL_SMUDGE_FACTOR = 0.8
DEFAULT_TAG_SMUDGE_FACTOR = 1.0
CONVERTED_FILE_ENDING = "radiance.tif"
